const arrNumber1 =[
    {},

    {
        anxious : "xavotirlangan",
        // awful : "juda yomon",
        consist : "iborat bo'lmoq",
        desire : "xoxlamoq",
        eager : "chanqoq, sabrsiz",
        household : "oila a'zolar",
        intent : "maqsad, niyat",
        landscape :" landshaft, manzara",
        lift : "ko'tarmoq",
        load : "yuklamoq",
        lung : "o'pka",
        motion : "harakat",
        // pace : "temp, sur'at",
        polite :" muloyim, odobli",
        possess : "egalik qilmoq",
        rapidly : "juda tez",
        remark : "ta'kidlamoq",
        seek :" qidirmoq",
        shine : "nur taratmoq",
        spill : "to'kib yubormoq",
         
    },
    {
        bring : "olib kelmoq",
        castle : "qasr",
        command : "buyruq bermoq",
        // counsel : "maslahat bermoq",
        ensure : "taminlamoq",
        explosion :" portlash",
        jewelry : "taqinchoq",
        land : "qo'nmoq",
        meteor :" metiorit",
        monster : "mahluq",
        northern : "shimoliy",
        remote : "olis, uzoq , masofaviy",
        southern : "janubiy",
        statue : "haykal",
        steam : "par, bug'",
        submit : "bo'ysunmoq",
        temple : "ibodatxona",
        upper : "yuqori",
        weed : "begona o't",
        wing : "qanot",
    },
    {
        arrow : "o'q, yoy",
        battle : "urush",
        // bow : "kamon",
        brave : "qo'rqmas, jasur",
        chief : "boshliq, sardor",
        disadvantage : "kamchilik",
        enemy : "dushman",
        entrance : "kirish yo'li",
        hardly : "arang, zo'rg'a",
        // intend : "niyat qilmoq",
        // laugher : "kulgi, shodlik",
        // log : "jurnal",
        military : "armiya",
        obey :" bo'ysunmoq",
        secure : "qo'lga kiritmoq",
        steady : "barqaror",
        trust : "ishonmoq",
        twist : "aylantirib bog'lamoq",
        unless : "magan taqdirda",
        weapon : "qurol-yarog'"
        
        
    },
    {
        chest : "ko'krak qafasi",
        confidence : "ishonch",
        consequence : "natija, oqibat",
        disaster : "falokat",
     
        estimate : "taxminan baholamoq",
        honor : "sharaflamoq",
        impress : "lol qoldirmoq",
        marathon : "marafon",
        narrow : "tor",
        pale : "xira",
        rough : "qo'pol",
        satisfy : "qoniqtirmoq",
        scream : "baqirmoq",
        sensitive : "ta'sirchan",
        shade : "soya",
        supplement : "qo'shmoq",
        terror : "qo'rquv",
        threat : "xavf, xatar",
        victim : "qurbon",
    },
    {
        ancestor : "ajdod",
        angle : "tomon, burchak",
        boot : "etik",
        border : "chegara",
        congratulate : "tabriklamoq",
        frame : "ramka",
        heaven : "jannat",
        incredible : "aqlga sig'mas",
        legend : "afsona",
        praise : "maqtamoq",
        proceed : "maqsad",
        pure : "sof, musaffo",
        relative : "qarindosh",
        senior : "katta yoshdagi",
        silent : "tinch",
        // sink : "cho'kmoq",
        superior : "yuqori",
        surround :" o'rab olmoq",
        thick : "qalin",
        wrap : "o'ramoq"
    },
    {
        abroad : "xorij, chet",
        anger : "jahlini chiqarmoq",
        bride : "kelinchak",
        brief : "qisqa",
        chase : "quvlamoq",
        disappoint : "hafa qilmoq",
        dive : "suvga sakramoq",
        exchange : "ayriboshlamoq",
        favor : "yordam",
        fee : "to'lov, badal",
        forever : "abadiy",
        guy : "erkak kishi",
        lovely : "yoqimli, go'zal",
        mood : "kayfiyat",
        palace : "qasr, saroy",
        permit : "ruxsat bermoq",
        protest : "norozilik bildirmoq",
        sculpture : "haykal",
        tribe : "qabila",
        youth : "yoshlik payt",
    },
    {
        basis : "asos",
        biology : "biologiya",
        case : "qafas",
        colleague : "hamkasb",
        colony : "kaloniya",
        debate :" muhokama qilmoq",
        depart : "jo'nab ketmoq",
        // depress : "hafa qilmoq",
        factual : "asosli, dalilga boy",
        fascinate : "maftun qilmoq",
        mission : "topshiriq",
        nevertheless : "shunga qaramay",
        occupation : "kasb",
        overseas : "okean orti",
        persuade : "ko'ndirmoq",
        route : "yo'nalish",
        ruins : "xaroba",
        scholar : "bilimdon",
        significant : "muhim",
        volcano : "vulqon",
    },
    {
        broad : "keng, katta",
        bush : "buta",
        capable : "qobiliyatli",
        cheat : "g'irromlik qilmoq",
        concentrate : "diqqatni jamlamoq",
        conclude :" deb xulosa qilmoq",
        confident : "o'ziga ishongan",
        considerably : "sezilarli",
        convey : "ifodalamoq",
        definite : "aniq, yaqqol",
        delight : "zavq, shavq",
        destination : "manzil",
        dictate : "aytib yozdirmoq",
        edge : "chet, qirra",
        // path : "yo'l",
        resort : "asoslanmoq",
        shadow : "soya",
        succeed : "muvaffaqiyat qozonmoq",
        suspect : "deb hisoblamoq",
        valley : "vodiy",
        
    },
    {
        admire : "qoyil qolmoq",
        // aid : "yordam bermoq",
        attempt :" harakat qilmoq",
        authority : "vakolat, huquq",
        capital : "poytaxt",
        cooperate : "hamkorlik qilmoq",
        defend : "mudofaa qilmoq",
        destruction : "vayrona",
        disorder : "tartibsizlik",
        division : "bo'lish",
        enable : "imkoniyat bermoq",
        frustrate : "umidsizlantirmoq",
        // govern : "boshqarmoq",
        plenty : "yetarli miqdor",
        relieve : "yengillashtirmoq",
        reputation : "obro'",
        royal : "qirollik",
        slave : "qul",
        struggle : "kurashmoq",
        stupid : "ahmoq",
    },
    {
        citizen : "fuqaro",
        council : "kengash, konsullik",
        declare : "elon qilish",
        // enourmous : "ulkan",
        extraordinary : "g'ayritabiiy",
        fog : "tuman",
        funeral : "dafn marosimi",
        giant : "ulkan, bahaybat",
        // imperession : "taassurot",
        income : "daromad",
        // mad : "badjahil",
        // ought : "kerak, lozim",
        resist : "qarshilik ko'rsatmoq",
        reveal : "ko'rsatmoq",
        // rid : "xalos qilmoq",
        sword : "qilich",
        // tale : "ertak",
        trap : "tutqunlikda saqlamoq",
        trial : "sud jarayoni",
        violent : "zo'ravon, quturgan"
    },
    {
        admission :" ruxsat, kirish",
        astronomy : "astonomiya",
        blame : "ayblamoq",
        chemistry : "kimyo",
        despite : "ga qaramasdan",
        dinosaur : "dinozavr",
        exhibit : "eksponat, ko'rgazma",
        // fame : "shon-shuhrat, obro",
        forecast : "ob-havo ma'lumoti",
        genius : "juda aqlli",
        gentle : "muloyim, yuvosh",
        geography : "geografiya",
        interfere : "halaqit bermoq",
       
        principal : "maktab direktori",
        // row : "qator",
        shelf : "tokcha",
        spite : "qasddan, ataylab",
        super : "juda yaxshi",
        wet : "nam, ho'l",
    },
    {
        // abuse : "haqorat qilmoq",
        afford : "qurbi yetmoq",
        bake : "pishirmoq",
        // bean : "noxat, loviya",
        candle : "sham",
        convert : "ga aylantirmoq",
        // debt : "qarz",
        decrease : "kamaytirmoq",
        fault : "xato, ayb",
        fund : "fond",
        generous : "sahiy, qo'li ochiq",
        ingredient : "tarkibiy qism",
        insist : "talab qilmoq",
        // mess :" kir, tartibsizlik",
        metal : "metal, temir",
        monitor :" kuzatib bormoq",
        oppose : "qarshi chiqmoq",
        passive :" passiv, sust",
        quantity : "miqdor",
        sue : "sudga bermoq",
    },
    {
        anxiety : "tashvish, g'am",
        army : "armiya",
        billion : "milliard",
        // carve : "kesmoq, tog'ramoq",
        consult : "yordam so'ramoq",
        emergency : "favqulodda vaziyat",
        fortune : "omad",
        guarantee : "kafolat bermoq",
        hike : "piyoda yurmoq",
        initial : "birinchi, dastlabki",
        intense : "jadal",
        peak : "cho'qqi",
        // lend : "qarz berib turmoq",
        potential : "ehtimoliy, potensial",
        pride : "mamnuniyat , g'urur",
        proof : "isbot, dalil",
        quit : "to'xtamoq , tark etmoq",
        spin : "aylanmoq",
        tiny : "kichik , mayda",
        tutor : "repititor , tarbiyachi",
    },
    {
        apparent : "aniq, muqarrar",
        blind : "ko'r, ko'zi ojiz",
        calculate : "hisoblamoq",
        chat : "suhbatlashmoq",
        commit : "va'da bermoq",
        compose : "tuzmoq, yaratmoq",
        dormitory : "yotoqxona",
        exhaust : "holdan toydirmoq",
        greenhouse : "issiqxona",
        ignore : "e'tiborsiz qoldirmoq",
        obvious : "aniq, ravshan",
        physics : "fizika",
        // porsion : "qism, bo'lak",
        remind : "eslatmoq",
        secretary : "kotib(a)",
        severe : "qattiq, jiddiy",
        talent : "iqtidor",
        thesis : "teziz",
        uniform : "forma",
        vision : "ko'rish qobilyati",
    }, 
    {
        absorb : "so'rmoq, shimmoq",
        // boss : "xo'jayin",
        // commite : "qo'mita, komitet",
        contract : "shartnoma",
        crew : "ekipaj",
        devote : "bag'ishlamoq",
        dig : "kavlamoq",
        // dine : "tushlik qilmoq",
        donate : "hadya qilmoq",
        double : "ikki hissa",
        elevate : "balandroqqa qo'ymoq",
        flavor : "ta'm, maza",
        foundation : "jamg'arma",
        generation : "avlod",
        handle : "band, tutqich",
        layer : "qatlam",
        mud : "loy",
        smooth : "tekis",
        soil : "tuproq",
        unique : "o'zgacha, g'ayrioddiy",
    },
    {
        chamber : "yotoqxona",
        deny : "inkor qilmoq",
        document : "hujjat",
        emphasize : "ta'kidlamoq",
        fever : "isitma",
        flu : "gripp",
        freeze : "muzlamoq",
        gesture : "imo-ishora",
        interrupt : "bezovta qilmoq",
        last : "oxirgi",
        likeness : "o'xshashlik",
        moreover : "bundan tashqari",
        perspective : "dunyoqarash",
        rational : "ongli",
        recover : "qayta tiklanmoq",
        rely : "suyanmoq, tayanmoq",
        shock : "hayratda qoldirmoq",
        shy : "uyatchan",
        stare : "tikilmoq",
        thus : "shuning uchun"
    },
    {
        aim : "maqsad",
        attach : "mahkamlamoq , biriktir",
        // bet : "pul tikmoq",
        carriage : "ot arava",
        classic : "odatiy",
        commute : "piyoda yurmoq",
        confirm : "tasdiqlamoq",
        criticize : "tanqid qilmoq",
        
        differ : "farq qilmoq",
        expense : "chiqim, xarajat",
        formal : "rasmiy",
        height : "bo'y",
        invent : "ixtiro qilmoq",
        junior : "kichik",
        labor : "mehnat",
        mechanic : "mexanik",
        prime : "birinchi, bosh",
        shift : "joyini o'zgartirmoq",
        signal : "belgi, signal",
        sincere : "samimiy"
    },
    {
        ability : "qobiliyat, iste'dod",
        agriculture : "qishloq xo'jaligi",
        cartoon : "multfilm",
        ceiling : "shift, patalok",
        convince : "ishontirmoq",
        curious : "qiziqqon",
        delay : "kechiktirmoq",
        diary : "kundalik",
        element : "element",
        faith : "imon",
        grain : "don",
        // greet : "salomlashmoq",
        investigate : "o'rganib chiqmoq",
        joy : "shodlik",
        // lebel : "yorliq",
        monk : "rohib",
        odd : "noodatiy",
        pause : "to'xtamoq",
        priest : "ruhoniy",
        profession : "kasb"
    },

    {
        adopt : "farzandlikka olmoq",
        beg : "sadaqa so'ramoq",
        beyond : "narigi tarafida",
        costume : "kiyim",
        exclaim : "xitob qilmoq",
        extend : "uzaytrish",
        fool : "ahmoq",
        forbid : "taqiqlamoq",
        illustrate : "ko'rsatmoq",
        indeed : "haqiqatda",
        interpret : "izohlamoq",
        kindly : "muloyimlik bilan",
        motive : "sabab",
        nest : "uya",
        origin : "kelib chiqish",
        reception : "to'y marosimi",
        reject : "rad etmoq",
        silence : "jimlik",
        stream : "daryocha",
        tone : "ovoz, ohang"
    },
    {
        accomplish : "bajarmoq",
        approve : "maqullamoq",
        approximate : "deyarli to'g'ri, taxminiy",
        barrier : "to'siq",
        detect : "sezmoq",
        duty : "burch, vazifa",
        elementary :" boshlang'ich",
        failure : "muvaffaqiyatsizlik",
        gradual : "bosqichma-bosqich",
        immigrant : "imigrant",
        insert : "ichiga qo'ymoq",
        instant : "on, lahza",
        poverty : "qashshoqlik",
        pretend : "dek tutmoq",
        rank : "martaba, unvon",
        recognition : "tan olish",
        refrigerate : "muzlatgichda saqlash",
        rent : "ijara haqi",
        retire : "iste'foga chiqmoq",
        statistic : "statistika"
    },
    {
        astronaut : "astranavt",
        // awake : "uyg'oq",
        courage : "botirlik",
        float : "suv ustida suzmoq",
        grant : "bermoq",
        gravity : "gravitatsiya",
        jewel : "qimmatbaho tosh",
        miner : "konchi",
        mineral : "mineral",
        participate : "ishtirok etmoq",
        permission : "ruxsat",
        // pour : "quymoq",
        presence : "bor bo'lish",
        // raw : "xom, pishmagan",
        // sattelite : "sun'iy yo'ldosh",
        scale : "kattalik",
        skip : "o'tkazib yubormoq",
        stretch : "cho'zmoq",
        telescope : "teleskop",
        underground : "yer ostida",
    },
    {
        alarm : "signalizatsiya",
        apart : "alohida",
        arrest : "hibsga olmoq",
        award : "mukofot, sovrin",
        breed : "zod, nasl",
        bucket : "chelak, paqir",
        contest : "musobaqa",
        convict : "hukm qilmoq",
        garage : "garaj",
        journalist : "jurnalist",
        //pup : "kuchuk",
        qualify : "o'zgartirmoq",
        repair : "tamirlamoq",
        resume : "davom ettirmoq",
        rob : "o'g'irlamoq",
        // slip : "sirpanib ketmoq",
        somewhat : "biroz",
        stable : "mustahkam",
        tissue : "salfetka",
        yard : "ochiq maydon",
    },
    {
        alike : "o'xshash",
        annoy : "achchiqlantirmoq",
        architecture : "arxitektura",
        artificial : "sun'iy",
        chain : "zanjir",
        distinct : "farqli",
        distinguish : "ajratmoq",
        dust : "chang",
        excitement : "hursandchilik",
        heal: "tuzalmoq",
        inherit : "meros qilib olmoq",
        manner : "o'zini tutish tarzi",
        mount : "ko'paytirmoq",
        roof : "tom" ,
        shortage : "tanqislik",
        solid : "qattiq",
        stock : "zahira",
        substance : "modda",
        tomb : "qabr",
        wound : "jarohat",
    },
    {
        bath : "vanna",
        bend : "bukmoq",
        //chew : "chaynamoq",
        disabled : "nogiron",
        fantastic : "ajoyib",
        fiction : "fantastik asar",
        flag : "bayroq",
        inspect : "tekshirmoq",
        journal : "jurnal",
        liquid : "suyuqlik",
        marvel : "hayron qolmoq",
        nutrient : "ozuqa",
        overcome : "ustun kelmoq",
        recall : "eslamoq",
        regret : "afsuslanmoq",
        soul : "ruh",
        sufficient : "yetarli",
        surgery : "jarrohlik",
        tough : "qattiq",
        tube : "quvur",
    },
    {
        admit : "tan olmoq",
      //  bin : "quti",
       // bowl : "kosa",
        // cabin : "kulba",
        // cash : "naqd pul",
        // criminal : "jinoyatchi",
        // dozen : "o'n ikkita",
        // elder : "yoshi katta",
        // facial : "yuzdagi",
        // fence : "panjara",
        // inspire : "ilhomlantirmoq",
        // mere : "arzimagan",
        neat : "toza",
        occasion : "voqea",
        penalty : "jarima",
        rude : "qo'pol",
        settle : "hal qilmoq",
        vehicle : "transport vositasi",
        wallet : "hamyon",
        yell : "dodlamoq",
    },
    {
        accuse : "ayblamoq",
        adjust : "o'zgartirmoq",
        amuse : "qiziqtirmoq",
        coral : "marjon",
        cotton : "paxta",
        crash: "to'qnashmoq",
        deck : "paluba",
        engage : "shug'illanish",
        firm : "mustahkam, qattiq",
        fuel : "yonilg'i",
        // grand : "hashamatli" ,
        // hurricane : "kuchli dovul ",
        // loss : "yo'qotish" ,
        // plain : "oddiy" ,
        // reef : "cho'g'irtosh, rif ",
        // shut : "yopib qo'ymoq ",
        // strict : "qattiqqo'l, talabchan ",
        // surf : "syorfing uchmoq ",
        // task : "vazifa, ish",
        // zone : "hudud",
    },
    {
        apology : "uzr, kechirim",
        bold : "botir",
        capture : "tutmoq",
        cardinal : "asosiy",
        duke : "gersog",
        expose : "oshkor qilmoq",
        guilty : "aybdor",
        hire : "yonlamoq",
        innocent : "aybsiz",
        jail : "qamoqxona",
        minister : "vazir",
        ordinary : "odatiy",
        permanent : "o'zgarmas",
        preserve : "saqlamoq",
        pronounce : "talafuz qilmoq",
        resemble : "o'xshamoq",
        symptom : "alomat",
        tobacco : "tamaki",
        twin : "egizaklar",
        witch : "jodugar",
    },
    {
       
        branch : "shox",
        breath : "nafas",
        bridge : "ko'prik",
        cast : "otmoq, uloqtirmoq",
        dare : "jurat qilmoq",
        electronic : "elektron",
        // inn : "mehmonxona",
        net : "to'r",
        philosophy : "falsafa",
        pot : "qozon",
        seed : "urug'",
        sharp : "o'tkir",
        sort : "tur, nav",
        subtract : "ayirmoq",
        tight : "tarang",
        virtual : "virtual",
        weigh : "vaznga ega bo'lmoq",
        whisper : "pichirlamoq",
    },
    {
        abstract : "mavhum",
        annual : "yillik",
        clay : "gil",
        cloth : "gazlama",
        curtain : "parda",
        deserve : "sazovor bo'lmoq",
        feather : "pat",
        fertile : "unumdor",
        flood : "suv toshqini",
        furniture : "mebel",
        grave : "qabr",
        ideal : "ideal",
        intelligence : "o'qimishlilik",
        nowadays : "hozirgi paytda",
        obtain : "qo'lga kiritmoq",
        religious : "diniy",
        romantic : "romantik",
        shell : "chig'anoq",
        shore : "qirg'oq",
        wheel : "g'ildirak",
    },
    {
        appeal : "jalb qilmoq",
        assume : "taxmin qilmoq",
        borrow : "qarz olmoq",
        client : "mijoz",
        downtown : "shaxar markazi",
        dull : "zerikarli",
        embarrass : "uyaltirmoq",
        fare : "yo'l haqi",
        former : "oldingi sobiq",
        formula : "formula",
        found : "asos solmoq",
        invest : "pul sarf qilmoq",
        loan : "qarz bermoq",
        practical : "foydali",
        quarter :"25 sentlik tanga",
        salary : "maosh",
        scholarship : "stependiya",
        temporary : "vaqtinchalik",
        treasure : "xazina",
        urge : "undamoq",
    }

 



]


const arrNumber2 =[
    {},

    {
        arise : "yuzaga kelmoq ",
        benefactor : "ko'mak beruvchi ",
        blacksmith : "temirchi" ,
        charitable : "ochiqqo'l",
        chimney : "mo'ri ",
        compensate : "qoplamoq" ,
        encounter : "duch kelmoq ",
        exceed : "oshib ketmoq" ,
        forge : "shakllantirmoq" ,
        humble : "kamtarin" ,
        iron : "temir" ,
        ladder : "narvon" ,
        modest : "kamtarin" ,
        occupy : "yashamoq" ,
        penny : "chaqa" ,
        preach : "voizlik qilmoq ",
        prosper : "yashnamoq",
        province : "viloyat" ,
        satisfaction : "mamnuniyat" ,
        sustain : "davom ettirmoq"
         
    },
    {

        acquire : "ega bo'lmoq ",
        awkward : "noqulay" ,
        caretaker : "enaga" ,
        deceive : "aldamoq",
        discourage : "tushkunlikka solmoq",
        fake : "soxta" ,
        hatred : "nafrat" ,
        hut : "kulba" ,
        inferior : "past" ,
        lodge : "kulba" ,
        neglect : "beparvolik qilmoq ",
        newcomer : "yangi kelgan ",
        offense : "jinoyat" ,
        overlook :" e'tiborsizlik ",
        repay : "qaytarish" ,
        ridiculous : "kulgili", 
        satisfactory : "qoniqarli" ,
        shepherd : "cho'pon ",
        venture : "oshiqmoq" ,
        wheat : "bug'doy"

    }

]